[package]
name = "sathgendashboard"
version = "1.0.0"
description = "Sathgen Dashboard"
authors = ["Godavari Biorefineries Inc"]
edition = "2021"

[lib]
name = "sathgendashboard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "sathgendashboard"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
